# Generated by Django 3.1.7 on 2021-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210324_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('code', 'code'), ('travel_vlogs', 'travel_vlogs'), ('food_vlogs', 'food_vlogs'), ('comedy', 'comedy'), ('gaming', 'gaming'), ('cooking', 'cooking'), ('academic', 'academic'), ('educational', 'educational')], max_length=255),
        ),
    ]
